### ISSUE TITLE
Overlay

### ISSUE THREAD

**Issue by cdrbbt** [villeloh/ArInvaders#4]
The bottom overlay seems large for something that has no functionality, maybe it would be better to make it smaller or semi-transparent

**Comment by e1337us3r** [comment]
Big chunk of the bottom overlay was removed and replaced with a gun. See commit : [07529f63b504aeff6a08810586fac1cb928409bc](https://github.com/villeloh/ArInvaders/commit/07529f63b504aeff6a08810586fac1cb928409bc)
